{
 "title": "Observabilidade - API Oficina",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "P95 - Latência da autenticação",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{http_target=\"/api/v1/auth/token\",http_method=\"POST\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "P99 - Latência da autenticação",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{http_target=\"/api/v1/auth/token\",http_method=\"POST\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Requisições de autenticação por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_target=\"/api/v1/auth/token\",http_method=\"POST\"}[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Total acumulado de autenticações (1h)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{http_target=\"/api/v1/auth/token\",http_method=\"POST\"}[1h]))"
    }
   ]
  },
  {
   "title": "Erros de autenticação por segundo",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 11, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_target=\"/api/v1/auth/token\",http_method=\"POST\", http_status_code=~\"4..|5..\"}[1m]))",
     "legendFormat": "errors/s"
    }
   ]
  },
  {
   "title": "Requisições HTTP ativas",
   "type": "stat",
   "gridPos": { "x": 12, "y": 11, "w": 12, "h": 5 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests)"
    }
   ]
  },
  {
   "title": "Conexões DB em uso",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 5 },
   "targets": [
    {
     "expr": "sum(db_client_connections_usage{state=\"used\"})"
    }
   ]
  }
 ]
}